name: 01 - Building Blocks
on: 
  workflow_dispatch:

jobs:
  echo-hello:
   runs-on: ubuntu-latest
   steps:
    - name: Say hello
      run: echo "Hello,World!"
  echo-goodbye:
   runs-on: ubuntu-latest
   steps:
    - name: First step
      run: |
       echo "I"
       echo "will"
       echo "fail"
       exit 0
    - name: Say goodbye
      run: printf "Goodbye!"